### ISSUE TITLE
ATF Execution pauses when browser tab running the Client Runner is moved to background

### ISSUE THREAD

**Issue by ramyaramdasan** [ServiceNow/sncicd-tests-run#11]
Hi,

It was observed many a times that if the browser tab running the Client Runner is moved to background, the ATF execution pauses. If we miss bringing it to the foreground, the workflow at times fails at the ATF step. And if we notice that workflow is taking unusually longer to finish ATF execution and switch to the tab with the runner, it will run quickly, as though fast forwarded, and complete the execution. I doubt if it is a pre-requirement to keep the Scheduled Client Runner in an active browser tab, because I have had successful pipeline executions too without doing so. Is this a known issue? 

Thanks
Ramya

**Comment by chiarnglin** [comment]
Hi Ramya!
Technically, any client UI tests in your ATF test suite will require a Scheduled Client Test Runner in an active browser tab/window. Different browsers have different logic/behavior for what qualifies as active vs inactive browser windows/tabs, or how much compute resources to dedicate to each tab, so that might result in some of the variation in behavior you've noticed. Otherwise, Headless Browser for ATF is the solution we should have you guys try once we get your instances to a Rome track.
Thanks!
Chiarng
